import{SvelteComponent,append_hydration,attr,children,claim_element,claim_space,claim_text,detach,element,init,insert_hydration,noop,safe_not_equal,space,src_url_equal,text}from"../../web_modules/svelte/internal/index.mjs";function create_fragment(){let a,g,s,p,o,b,y,V,l,d,c,h,m,r,W,R,v,n,f,L,O,t,w,x,C,E,k,A,S,M,F,T,z,D,N,_,j,P,H,I,B,u,i,$;return{c(){a=element("section"),g=element("div"),s=element("div"),p=element("div"),o=element("div"),b=element("div"),y=element("div"),V=space(),l=element("div"),d=element("div"),c=element("div"),h=element("div"),m=element("div"),r=element("img"),R=space(),v=element("div"),n=element("div"),f=element("h4"),L=text("I'm sociable…flexible & thoughtful."),O=space(),t=element("p"),w=text(`I am a sociable lady who loves to be with people, to talk, to
            entertain and to listen. I have a teaching background, I have taught
            in high schools and more recently I taught English to adults from
            diverse cultural backgrounds.
            `),x=element("br"),C=element("br"),E=text(`
            Throught these experiences I have gained many insights into the importance
            of cultural, beliefs and customs. From my own multi-cultural background,
            I can empathize with difficulties that arise due to language barriers
            in adapting to a new country. `),k=element("br"),A=element("br"),S=text(`
            I understand the importance of blending the legal requirements to marry
            in Australia to traditional religious ceremonies and I am happy to be
            a part of this and design a personal ceremony for you. I believe that with
            the skills that I have developed, I can offer you clear communication
            and at the same time I’ll be flexible and thoughtful to your personal,
            family or cultural needs.`),M=element("br"),F=element("br"),T=text(` With Marriage Equality, I am
            happy to perform marriages for same sex couples and also Naming Day
            and Renewal of Vows Ceremonies.`),z=element("br"),D=element("br"),N=space(),_=element("small"),j=element("em"),P=text(`I offer you a no obligation meeting, simply a chat for you to
                meet me, before you make your decision.`),H=space(),I=element("br"),B=space(),u=element("div"),i=element("a"),$=text("My Services"),this.h()},l(e){a=claim_element(e,"SECTION",{class:!0});var W,U,K,q,Y,G,X,Q,Z,J,ce=children(a),oe,ne,ee,te,se,ie,ae,re;g=claim_element(ce,"DIV",{class:!0}),oe=children(g),s=claim_element(oe,"DIV",{class:!0}),q=children(s),p=claim_element(q,"DIV",{class:!0}),ne=children(p),o=claim_element(ne,"DIV",{class:!0}),K=children(o),b=claim_element(K,"DIV",{class:!0}),G=children(b),y=claim_element(G,"DIV",{class:!0}),children(y).forEach(detach),G.forEach(detach),V=claim_space(K),l=claim_element(K,"DIV",{class:!0}),X=children(l),d=claim_element(X,"DIV",{class:!0}),Q=children(d),c=claim_element(Q,"DIV",{class:!0}),Z=children(c),h=claim_element(Z,"DIV",{class:!0}),J=children(h),m=claim_element(J,"DIV",{class:!0}),ee=children(m),r=claim_element(ee,"IMG",{class:!0,src:!0,alt:!0}),ee.forEach(detach),J.forEach(detach),Z.forEach(detach),Q.forEach(detach),X.forEach(detach),K.forEach(detach),ne.forEach(detach),R=claim_space(q),v=claim_element(q,"DIV",{class:!0}),te=children(v),n=claim_element(te,"DIV",{class:!0}),U=children(n),f=claim_element(U,"H4",{class:!0}),se=children(f),L=claim_text(se,"I'm sociable…flexible & thoughtful."),se.forEach(detach),O=claim_space(U),t=claim_element(U,"P",{}),W=children(t),w=claim_text(W,`I am a sociable lady who loves to be with people, to talk, to
            entertain and to listen. I have a teaching background, I have taught
            in high schools and more recently I taught English to adults from
            diverse cultural backgrounds.
            `),x=claim_element(W,"BR",{}),C=claim_element(W,"BR",{}),E=claim_text(W,`
            Throught these experiences I have gained many insights into the importance
            of cultural, beliefs and customs. From my own multi-cultural background,
            I can empathize with difficulties that arise due to language barriers
            in adapting to a new country. `),k=claim_element(W,"BR",{}),A=claim_element(W,"BR",{}),S=claim_text(W,`
            I understand the importance of blending the legal requirements to marry
            in Australia to traditional religious ceremonies and I am happy to be
            a part of this and design a personal ceremony for you. I believe that with
            the skills that I have developed, I can offer you clear communication
            and at the same time I’ll be flexible and thoughtful to your personal,
            family or cultural needs.`),M=claim_element(W,"BR",{}),F=claim_element(W,"BR",{}),T=claim_text(W,` With Marriage Equality, I am
            happy to perform marriages for same sex couples and also Naming Day
            and Renewal of Vows Ceremonies.`),z=claim_element(W,"BR",{}),D=claim_element(W,"BR",{}),N=claim_space(W),_=claim_element(W,"SMALL",{}),ie=children(_),j=claim_element(ie,"EM",{}),ae=children(j),P=claim_text(ae,`I offer you a no obligation meeting, simply a chat for you to
                meet me, before you make your decision.`),ae.forEach(detach),ie.forEach(detach),H=claim_space(W),W.forEach(detach),I=claim_element(U,"BR",{}),B=claim_space(U),u=claim_element(U,"DIV",{class:!0}),re=children(u),i=claim_element(re,"A",{class:!0,href:!0}),Y=children(i),$=claim_text(Y,"My Services"),Y.forEach(detach),re.forEach(detach),U.forEach(detach),te.forEach(detach),q.forEach(detach),oe.forEach(detach),ce.forEach(detach),this.h()},h(){attr(y,"class","ttm-col-wrapper-bg-layer-inner"),attr(b,"class","ttm-col-wrapper-bg-layer ttm-bg-layer"),attr(r,"class","img-fluid mb_50"),src_url_equal(r.src,W="media/about/wedding_about01.jpeg")||attr(r,"src",W),attr(r,"alt","single_07"),attr(m,"class","ttm_single_image-wrapper text-lg-left text-center"),attr(h,"class","pt-30 pl-30 mr_65 text-center"),attr(c,"class","layer-content"),attr(d,"class","ttm-col-bgcolor-yes ttm-bgcolor-white ttm-col-bgimage-yes"),attr(l,"class","layer-content"),attr(o,"class","ttm-col-bgcolor-yes ttm-bg ttm-bgcolor-skincolor spacing-10 h-auto"),attr(p,"class","col-lg-5 col-sm-5"),attr(f,"class","title"),attr(i,"class","ttm-btn ttm-btn-size-md ttm-btn-shape-rounded ttm-btn-style-border ttm-icon-btn-right ttm-btn-color-dark res-991-mb-25"),attr(i,"href","service"),attr(u,"class","mt-10 btn-center svelte-izqdu"),attr(n,"class","mt-0 res-991-mt-60"),attr(v,"class","col-lg-6 col-sm-12"),attr(s,"class","row"),attr(g,"class","container"),attr(a,"class","ttm-row about-top-section clearfix")},m(e,W){insert_hydration(e,a,W),append_hydration(a,g),append_hydration(g,s),append_hydration(s,p),append_hydration(p,o),append_hydration(o,b),append_hydration(b,y),append_hydration(o,V),append_hydration(o,l),append_hydration(l,d),append_hydration(d,c),append_hydration(c,h),append_hydration(h,m),append_hydration(m,r),append_hydration(s,R),append_hydration(s,v),append_hydration(v,n),append_hydration(n,f),append_hydration(f,L),append_hydration(n,O),append_hydration(n,t),append_hydration(t,w),append_hydration(t,x),append_hydration(t,C),append_hydration(t,E),append_hydration(t,k),append_hydration(t,A),append_hydration(t,S),append_hydration(t,M),append_hydration(t,F),append_hydration(t,T),append_hydration(t,z),append_hydration(t,D),append_hydration(t,N),append_hydration(t,_),append_hydration(_,j),append_hydration(j,P),append_hydration(t,H),append_hydration(n,I),append_hydration(n,B),append_hydration(n,u),append_hydration(u,i),append_hydration(i,$)},p:noop,i:noop,o:noop,d(e){e&&detach(a)}}}class Component extends SvelteComponent{constructor(e){super(),init(this,e,null,create_fragment,safe_not_equal,{})}}export default Component