import{SvelteComponent,append_hydration,attr,children,claim_element,claim_space,claim_text,detach,element,init,insert_hydration,noop,safe_not_equal,set_data,space,src_url_equal,text}from"../../web_modules/svelte/internal/index.mjs";function create_fragment(e){let r,f,i,b,a,v,_,q,h,d,u,c,m,s,E,C,K,l,n,p,x,U,t,W,$,P,A,S,R,M,F,T,z,D,N,L,j,y,H,I,B,V,g,o,w=e[2].title+"",O,k;return{c(){r=element("section"),f=element("div"),i=element("div"),b=element("div"),a=element("div"),v=element("div"),_=element("div"),q=space(),h=element("div"),d=element("div"),u=element("div"),c=element("div"),m=element("div"),s=element("img"),K=space(),l=element("div"),n=element("div"),p=element("h4"),x=text(e[0]),U=space(),t=element("p"),W=text(`I am a sociable lady who loves to be with people, to talk, to
            entertain and to listen. I have a teaching background, I have taught
            in high schools and more recently I taught English to adults from
            diverse cultural backgrounds.
            `),$=element("br"),P=element("br"),A=text(`
            Throught these experiences I have gained many insights into the importance
            of cultural, beliefs and customs. From my own multi-cultural background,
            I can empathize with difficulties that arise due to language barriers
            in adapting to a new country. `),S=element("br"),R=element("br"),M=text(`
            I understand the importance of blending the legal requirements to marry
            in Australia to traditional religious ceremonies and I am happy to be
            a part of this and design a personal ceremony for you. I believe that with
            the skills that I have developed, I can offer you clear communication
            and at the same time I’ll be flexible and thoughtful to your personal,
            family or cultural needs.`),F=element("br"),T=element("br"),z=text(` With Marriage Equality, I am
            happy to perform marriages for same sex couples and also Naming Day
            and Renewal of Vows Ceremonies.`),D=element("br"),N=element("br"),L=space(),j=element("small"),y=element("em"),H=text(`I offer you a no obligation meeting, simply a chat for you to
                meet me, before you make your decision.`),I=space(),B=element("br"),V=space(),g=element("div"),o=element("a"),O=text(w),this.h()},l(C){r=claim_element(C,"SECTION",{class:!0});var E,k,Y,G,X,Q,Z,J,de=children(r),ae,ne,ee,te,oe,ie,re,ce,le,se;f=claim_element(de,"DIV",{class:!0}),Q=children(f),i=claim_element(Q,"DIV",{class:!0}),G=children(i),b=claim_element(G,"DIV",{class:!0}),ae=children(b),a=claim_element(ae,"DIV",{class:!0}),Y=children(a),v=claim_element(Y,"DIV",{class:!0}),ne=children(v),_=claim_element(ne,"DIV",{class:!0}),children(_).forEach(detach),ne.forEach(detach),q=claim_space(Y),h=claim_element(Y,"DIV",{class:!0}),Z=children(h),d=claim_element(Z,"DIV",{class:!0}),J=children(d),u=claim_element(J,"DIV",{class:!0}),ee=children(u),c=claim_element(ee,"DIV",{class:!0}),te=children(c),m=claim_element(te,"DIV",{class:!0}),oe=children(m),s=claim_element(oe,"IMG",{class:!0,src:!0,alt:!0}),oe.forEach(detach),te.forEach(detach),ee.forEach(detach),J.forEach(detach),Z.forEach(detach),Y.forEach(detach),ae.forEach(detach),K=claim_space(G),l=claim_element(G,"DIV",{class:!0}),X=children(l),n=claim_element(X,"DIV",{class:!0}),k=children(n),p=claim_element(k,"H4",{class:!0}),ie=children(p),x=claim_text(ie,e[0]),ie.forEach(detach),U=claim_space(k),t=claim_element(k,"P",{}),E=children(t),W=claim_text(E,`I am a sociable lady who loves to be with people, to talk, to
            entertain and to listen. I have a teaching background, I have taught
            in high schools and more recently I taught English to adults from
            diverse cultural backgrounds.
            `),$=claim_element(E,"BR",{}),P=claim_element(E,"BR",{}),A=claim_text(E,`
            Throught these experiences I have gained many insights into the importance
            of cultural, beliefs and customs. From my own multi-cultural background,
            I can empathize with difficulties that arise due to language barriers
            in adapting to a new country. `),S=claim_element(E,"BR",{}),R=claim_element(E,"BR",{}),M=claim_text(E,`
            I understand the importance of blending the legal requirements to marry
            in Australia to traditional religious ceremonies and I am happy to be
            a part of this and design a personal ceremony for you. I believe that with
            the skills that I have developed, I can offer you clear communication
            and at the same time I’ll be flexible and thoughtful to your personal,
            family or cultural needs.`),F=claim_element(E,"BR",{}),T=claim_element(E,"BR",{}),z=claim_text(E,` With Marriage Equality, I am
            happy to perform marriages for same sex couples and also Naming Day
            and Renewal of Vows Ceremonies.`),D=claim_element(E,"BR",{}),N=claim_element(E,"BR",{}),L=claim_space(E),j=claim_element(E,"SMALL",{}),re=children(j),y=claim_element(re,"EM",{}),ce=children(y),H=claim_text(ce,`I offer you a no obligation meeting, simply a chat for you to
                meet me, before you make your decision.`),ce.forEach(detach),re.forEach(detach),I=claim_space(E),E.forEach(detach),B=claim_element(k,"BR",{}),V=claim_space(k),g=claim_element(k,"DIV",{class:!0}),le=children(g),o=claim_element(le,"A",{class:!0,href:!0}),se=children(o),O=claim_text(se,w),se.forEach(detach),le.forEach(detach),k.forEach(detach),X.forEach(detach),G.forEach(detach),Q.forEach(detach),de.forEach(detach),this.h()},h(){attr(_,"class","ttm-col-wrapper-bg-layer-inner"),attr(v,"class","ttm-col-wrapper-bg-layer ttm-bg-layer"),attr(s,"class","img-fluid mb_50"),src_url_equal(s.src,E=e[1].src)||attr(s,"src",E),attr(s,"alt",C=e[1].altText),attr(m,"class","ttm_single_image-wrapper text-lg-left text-center"),attr(c,"class","pt-30 pl-30 mr_65 text-center"),attr(u,"class","layer-content"),attr(d,"class","ttm-col-bgcolor-yes ttm-bgcolor-white ttm-col-bgimage-yes"),attr(h,"class","layer-content"),attr(a,"class","ttm-col-bgcolor-yes ttm-bg ttm-bgcolor-skincolor spacing-10 h-auto"),attr(b,"class","col-lg-5 col-sm-5"),attr(p,"class","title"),attr(o,"class","ttm-btn ttm-btn-size-md ttm-btn-shape-rounded ttm-btn-style-border ttm-icon-btn-right ttm-btn-color-dark res-991-mb-25"),attr(o,"href",k=e[2].url),attr(g,"class","mt-10 btn-center svelte-izqdu"),attr(n,"class","mt-0 res-991-mt-60"),attr(l,"class","col-lg-6 col-sm-12"),attr(i,"class","row"),attr(f,"class","container"),attr(r,"class","ttm-row about-top-section clearfix")},m(e,w){insert_hydration(e,r,w),append_hydration(r,f),append_hydration(f,i),append_hydration(i,b),append_hydration(b,a),append_hydration(a,v),append_hydration(v,_),append_hydration(a,q),append_hydration(a,h),append_hydration(h,d),append_hydration(d,u),append_hydration(u,c),append_hydration(c,m),append_hydration(m,s),append_hydration(i,K),append_hydration(i,l),append_hydration(l,n),append_hydration(n,p),append_hydration(p,x),append_hydration(n,U),append_hydration(n,t),append_hydration(t,W),append_hydration(t,$),append_hydration(t,P),append_hydration(t,A),append_hydration(t,S),append_hydration(t,R),append_hydration(t,M),append_hydration(t,F),append_hydration(t,T),append_hydration(t,z),append_hydration(t,D),append_hydration(t,N),append_hydration(t,L),append_hydration(t,j),append_hydration(j,y),append_hydration(y,H),append_hydration(t,I),append_hydration(n,B),append_hydration(n,V),append_hydration(n,g),append_hydration(g,o),append_hydration(o,O)},p(e,[t]){t&2&&!src_url_equal(s.src,E=e[1].src)&&attr(s,"src",E),t&2&&C!==(C=e[1].altText)&&attr(s,"alt",C),t&1&&set_data(x,e[0]),t&4&&w!==(w=e[2].title+"")&&set_data(O,w),t&4&&k!==(k=e[2].url)&&attr(o,"href",k)},i:noop,o:noop,d(e){e&&detach(r)}}}function instance(e,t,n){let{title:s,image:o,button:i}=t;return e.$$set=e=>{"title"in e&&n(0,s=e.title),"image"in e&&n(1,o=e.image),"button"in e&&n(2,i=e.button)},[s,o,i]}class Component extends SvelteComponent{constructor(e){super(),init(this,e,instance,create_fragment,safe_not_equal,{title:0,image:1,button:2})}}export default Component