import{SvelteComponent,append_hydration,attr,children,claim_element,claim_space,claim_text,detach,element,init,insert_hydration,noop,safe_not_equal,space,src_url_equal,text}from"../../web_modules/svelte/internal/index.mjs";function create_fragment(){let r,f,n,s,o,b,_,O,v,d,u,h,m,a,V,E,p,c,w,I,g,i,l,x,C,t,k,A,S,M,F,T,z,D,N,L,R,P,H,y,j,B;return{c(){r=element("section"),f=element("div"),n=element("div"),s=element("div"),o=element("div"),b=element("div"),_=element("div"),O=space(),v=element("div"),d=element("div"),u=element("div"),h=element("div"),m=element("div"),a=element("img"),E=space(),p=element("div"),c=element("a"),w=text("My Services"),I=space(),g=element("div"),i=element("div"),l=element("h4"),x=text("I'm sociable…flexible & thoughtful."),C=space(),t=element("p"),k=text(`I am a sociable lady who loves to be with people, to talk, to
            entertain and to listen. I have a teaching background, I have taught
            in high schools and more recently I taught English to adults from
            diverse cultural backgrounds.
            `),A=element("br"),S=element("br"),M=text(`
            Throught these experiences I have gained many insights into the importance
            of cultural. beliefs and customs. From my own multi-cultural background,
            I can empathize with difficulties that arise due to language barriers
            in adapting to a new country. `),F=element("br"),T=element("br"),z=text(`
            I understand the importance of blending the legal requirements to marry
            in Australia to traditional religious ceremonies and I am happy to be
            a part of this and design a ceremony fit for you. I believe that with
            the skills that I have developed, I can offer you clear communication
            and at the same time I’ll be flexible and thoughtful to your personal,
            family or cultural needs.`),D=element("br"),N=element("br"),L=text(` With Marriage Equality, I am
            happy to perform marriages for same sex couples and also Naming Day
            and Renewal of Vows Ceremonies.`),R=element("br"),P=element("br"),H=space(),y=element("small"),j=element("em"),B=text(`I offer you a no obligation meeting, simply a chat for you to
                meet me, before you make your decision.`),this.h()},l(e){r=claim_element(e,"SECTION",{class:!0});var V,$,W,U,K,q,Y,G,X,Q,Z,J,ae=children(r),oe,ne,ee,te,se,ie;f=claim_element(ae,"DIV",{class:!0}),oe=children(f),n=claim_element(oe,"DIV",{class:!0}),W=children(n),s=claim_element(W,"DIV",{class:!0}),U=children(s),o=claim_element(U,"DIV",{class:!0}),K=children(o),b=claim_element(K,"DIV",{class:!0}),ne=children(b),_=claim_element(ne,"DIV",{class:!0}),children(_).forEach(detach),ne.forEach(detach),O=claim_space(K),v=claim_element(K,"DIV",{class:!0}),Y=children(v),d=claim_element(Y,"DIV",{class:!0}),G=children(d),u=claim_element(G,"DIV",{class:!0}),X=children(u),h=claim_element(X,"DIV",{class:!0}),Q=children(h),m=claim_element(Q,"DIV",{class:!0}),Z=children(m),a=claim_element(Z,"IMG",{class:!0,src:!0,alt:!0}),Z.forEach(detach),Q.forEach(detach),X.forEach(detach),G.forEach(detach),Y.forEach(detach),K.forEach(detach),E=claim_space(U),p=claim_element(U,"DIV",{class:!0}),J=children(p),c=claim_element(J,"A",{class:!0,href:!0}),ee=children(c),w=claim_text(ee,"My Services"),ee.forEach(detach),J.forEach(detach),U.forEach(detach),I=claim_space(W),g=claim_element(W,"DIV",{class:!0}),te=children(g),i=claim_element(te,"DIV",{class:!0}),$=children(i),l=claim_element($,"H4",{class:!0}),se=children(l),x=claim_text(se,"I'm sociable…flexible & thoughtful."),se.forEach(detach),C=claim_space($),t=claim_element($,"P",{}),V=children(t),k=claim_text(V,`I am a sociable lady who loves to be with people, to talk, to
            entertain and to listen. I have a teaching background, I have taught
            in high schools and more recently I taught English to adults from
            diverse cultural backgrounds.
            `),A=claim_element(V,"BR",{}),S=claim_element(V,"BR",{}),M=claim_text(V,`
            Throught these experiences I have gained many insights into the importance
            of cultural. beliefs and customs. From my own multi-cultural background,
            I can empathize with difficulties that arise due to language barriers
            in adapting to a new country. `),F=claim_element(V,"BR",{}),T=claim_element(V,"BR",{}),z=claim_text(V,`
            I understand the importance of blending the legal requirements to marry
            in Australia to traditional religious ceremonies and I am happy to be
            a part of this and design a ceremony fit for you. I believe that with
            the skills that I have developed, I can offer you clear communication
            and at the same time I’ll be flexible and thoughtful to your personal,
            family or cultural needs.`),D=claim_element(V,"BR",{}),N=claim_element(V,"BR",{}),L=claim_text(V,` With Marriage Equality, I am
            happy to perform marriages for same sex couples and also Naming Day
            and Renewal of Vows Ceremonies.`),R=claim_element(V,"BR",{}),P=claim_element(V,"BR",{}),H=claim_space(V),y=claim_element(V,"SMALL",{}),ie=children(y),j=claim_element(ie,"EM",{}),q=children(j),B=claim_text(q,`I offer you a no obligation meeting, simply a chat for you to
                meet me, before you make your decision.`),q.forEach(detach),ie.forEach(detach),V.forEach(detach),$.forEach(detach),te.forEach(detach),W.forEach(detach),oe.forEach(detach),ae.forEach(detach),this.h()},h(){attr(_,"class","ttm-col-wrapper-bg-layer-inner"),attr(b,"class","ttm-col-wrapper-bg-layer ttm-bg-layer"),attr(a,"class","img-fluid mb_50"),src_url_equal(a.src,V="media/about/wedding_about01.jpeg")||attr(a,"src",V),attr(a,"alt","single_07"),attr(m,"class","ttm_single_image-wrapper text-lg-left text-center"),attr(h,"class","pt-30 pl-30 mr_65 text-center"),attr(u,"class","layer-content"),attr(d,"class","ttm-col-bgcolor-yes ttm-bgcolor-white ttm-col-bgimage-yes"),attr(v,"class","layer-content"),attr(o,"class","ttm-col-bgcolor-yes ttm-bg ttm-bgcolor-skincolor spacing-10 h-auto"),attr(c,"class","ttm-btn ttm-btn-size-md ttm-btn-shape-rounded ttm-btn-style-border ttm-icon-btn-right ttm-btn-color-dark res-991-mb-25"),attr(c,"href","service"),attr(p,"class","mt-10 btn-center svelte-169gtdl"),attr(s,"class","col-lg-5 col-sm-5"),attr(l,"class","title"),attr(i,"class","mt-0 res-991-mt-60"),attr(g,"class","col-lg-6 col-sm-12"),attr(n,"class","row"),attr(f,"class","container"),attr(r,"class","ttm-row about-top-section clearfix")},m(e,V){insert_hydration(e,r,V),append_hydration(r,f),append_hydration(f,n),append_hydration(n,s),append_hydration(s,o),append_hydration(o,b),append_hydration(b,_),append_hydration(o,O),append_hydration(o,v),append_hydration(v,d),append_hydration(d,u),append_hydration(u,h),append_hydration(h,m),append_hydration(m,a),append_hydration(s,E),append_hydration(s,p),append_hydration(p,c),append_hydration(c,w),append_hydration(n,I),append_hydration(n,g),append_hydration(g,i),append_hydration(i,l),append_hydration(l,x),append_hydration(i,C),append_hydration(i,t),append_hydration(t,k),append_hydration(t,A),append_hydration(t,S),append_hydration(t,M),append_hydration(t,F),append_hydration(t,T),append_hydration(t,z),append_hydration(t,D),append_hydration(t,N),append_hydration(t,L),append_hydration(t,R),append_hydration(t,P),append_hydration(t,H),append_hydration(t,y),append_hydration(y,j),append_hydration(j,B)},p:noop,i:noop,o:noop,d(e){e&&detach(r)}}}class Component extends SvelteComponent{constructor(e){super(),init(this,e,null,create_fragment,safe_not_equal,{})}}export default Component